spring:
  application:
    name: consumer
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: pulse.group
      auto-offset-reset: earliest
    listener:
      concurrency: 2
  data:
    redis:
      host: localhost
      port: 6379